export type Sentiment = 'positive' | 'negative' | 'neutral';
export type Platform = 'twitter' | 'instagram' | 'tiktok' | 'news';
export type Source = 'web' | 'instagram' | 'tiktok' | 'news';

export interface SocialPost {
  id: string;
  url: string;
  username: string;
  location: string;
  timeAgo: string;
  sentiment: Sentiment;
  content: string;
  likes: number;
  comments: number;
  platform: Platform;
  source: Source;
}

export const twitterPosts: SocialPost[] = [
  {
    id: '2048333766867730476',
    url: 'https://x.com/i/status/2048333766867730476',
    username: '@SINDOnews',
    location: 'Jakarta',
    timeAgo: '4:30 PM · 26 Apr 2026',
    sentiment: 'negative',
    content: 'Temuan pengurangan porsi dalam program Makan Bergizi Gratis (MBG) jadi sorotan. Sekitar 1.700 SPPG dihentikan sementara untuk evaluasi karena ada menu di bawah standar gizi. Hal ini berpotensi menurunkan kualitas asupan anak. #MBG #MakanBergiziGratis #GiziAnak',
    likes: 0,
    comments: 0,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2048056231928217678',
    url: 'https://x.com/i/status/2048056231928217678',
    username: '@ferizandra',
    location: 'Cianjur',
    timeAgo: '10:07 · 25 Apr 2026',
    sentiment: 'negative',
    content: 'Kasus dugaan keracunan terkait program MBG di Cianjur menjadi perhatian. Seorang balita (2 tahun) dilaporkan meninggal dunia setelah dirawat, sementara puluhan lainnya mengalami gejala serupa. Dinas Kesehatan masih menunggu hasil laboratorium untuk memastikan penyebabnya. #MBG #Cianjur #GiziAnak',
    likes: 1500,
    comments: 83,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047900199478350079',
    url: 'https://x.com/i/status/2047900199478350079',
    username: '@MurtadhaOne1',
    location: 'Jeneponto, Lombok Timur',
    timeAgo: '11:47 AM · 23 Apr 2026',
    sentiment: 'negative',
    content: 'Kasus dugaan keracunan terkait program MBG kembali menjadi sorotan di berbagai daerah. Laporan muncul dari Jeneponto (23 April) dan Lombok Timur (24 April), memicu kekhawatiran masyarakat terkait keamanan makanan yang diberikan kepada anak-anak. #MBG #KeamananPangan',
    likes: 412,
    comments: 218,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047594344832721093',
    url: 'https://x.com/i/status/2047594344832721093',
    username: '@menuembegejelek',
    location: 'Pangadaan, Lombok Timur',
    timeAgo: '2 jam lalu',
    sentiment: 'negative',
    content: '22 Siswa SD di Lombok Timur Diduga Keracunan Makanan MBG, Alami Mual hingga Kejang',
    likes: 17,
    comments: 715,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047569872108892629',
    url: 'https://x.com/i/status/2047569872108892629',
    username: '@ferizandra',
    location: 'Pringgasela, Lombok Timur',
    timeAgo: '1:54 PM · Apr 24 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG, 21 Siswa di Lombok Timur Alami Mual dan Muntah Usai Konsumsi Makanan',
    likes: 16,
    comments: 3,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2045748700795019647',
    url: 'https://x.com/i/status/2045748700795019647',
    username: '@menuemebegejelek',
    location: 'Cilegon, Banten',
    timeAgo: '16 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG di Cilegon, 49 Siswa MTs Al-Inayah Alami Mual dan Muntah, Puluhan Dirawat',
    likes: 255,
    comments: 8300,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2045034527870087508',
    url: 'https://x.com/i/status/2045034527870087508',
    username: '@tempodotco',
    location: 'Jakarta',
    timeAgo: '2:00 PM · 17 Apr 2026',
    sentiment: 'negative',
    content: 'Anggaran BGN Disorot, Rp1,5 Miliar Dihabiskan untuk Sikat dan Semir Sepatu',
    likes: 23000,
    comments: 3000,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042766137591763322',
    url: 'https://x.com/i/status/2042766137591763322',
    username: '@SumandoGaek',
    location: 'Jakarta',
    timeAgo: '7:46 AM · 11 Apr 2026',
    sentiment: 'negative',
    content: 'Anggaran MBG Diduga Bermasalah, Potensi Penyimpangan Disebut Terjadi pada Biaya Porsi Makanan',
    likes: 10,
    comments: 0,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042509805462655484',
    url: 'https://x.com/i/status/2042509805462655484',
    username: '@is_pelssy',
    location: 'Jambi',
    timeAgo: '1 hari lalu',
    sentiment: 'negative',
    content: 'Cicipi MBG Sebelum Dibagikan, 3 Guru Di SMPN 7 Jambi Keracunan Dan Dilarikan ke Rumah Sakit',
    likes: 6600,
    comments: 643,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042461329064415463',
    url: 'https://x.com/i/status/2042461329064415463',
    username: '@Txtdariiugm',
    location: 'Yogyakarta',
    timeAgo: '11:35 AM · Apr 10',
    sentiment: 'negative',
    content: 'Anggaran MBG Rp10 Ribu per Porsi Disorot, Dinilai Tidak Sebanding dengan Kualitas Makanan',
    likes: 9700,
    comments: 128,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042303365821116922',
    url: 'https://x.com/i/status/2042303365821116922',
    username: '@SumandoGaek',
    location: 'Medan',
    timeAgo: '1:07 AM · Apr 10 2026',
    sentiment: 'negative',
    content: 'Laporan dari Medan: Orang Tua di Medan Keluhkan Porsi MBG untuk Anak TK, Dinilai Tidak Layak dan Minim Gizi',
    likes: 4400,
    comments: 220,
    platform: 'twitter',
    source: 'web',
  },
];

export const instagramPosts: SocialPost[] = [
  {
    id: 'DXjetRFEith',
    url: 'https://www.instagram.com/reel/DXjetRFEith/',
    username: '@otistanews',
    location: 'Benteng, Bengkulu',
    timeAgo: '24 Apr 2026',
    sentiment: 'negative',
    content: 'Ayam terlihat fresh tapi berulat SPPG Kembang Seri distop, dugaan keracunan mencuat',
    likes: 1121,
    comments: 335,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXbNp3RERej',
    url: 'https://www.instagram.com/reel/DXbNp3RERej/',
    username: '@komunitaskabarmadura',
    location: 'Madura',
    timeAgo: '22 Apr 2026',
    sentiment: 'negative',
    content: 'Siswa di SDN Bira Tengah Sokobana Sampang usai makan MBG langsung alergi kulit, tiba-tiba merasa gatal-gatal',
    likes: 6558,
    comments: 1059,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVd2Lg1Ee5v',
    url: 'https://www.instagram.com/reel/DVd2Lg1Ee5v/',
    username: '@info.jabodetabek',
    location: 'Depok',
    timeAgo: '2 jam yang lalu',
    sentiment: 'negative',
    content: 'Menu MBG di Cinangka disorot, timun utuh dinilai kurang praktis untuk anak',
    likes: 6679,
    comments: 1944,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWl5cMSk6VO',
    url: 'https://www.instagram.com/reel/DWl5cMSk6VO/',
    username: '@tuntasnews',
    location: 'Cianjur',
    timeAgo: '6 Apr 2026',
    sentiment: 'negative',
    content: 'Menu MBG di Cianjur diduga ayam bau bangkai, siswa terancam',
    likes: 5790,
    comments: 1971,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVLRLL_Eeq7',
    url: 'https://www.instagram.com/reel/DVLRLL_Eeq7/',
    username: '@radarbromo',
    location: 'Magetan',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Kotor dan retak! telur MBG di Magetan di rebus masih ada kotoran ayam',
    likes: 69400,
    comments: 12100,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVvB98PkeDS',
    url: 'https://www.instagram.com/reel/DVvB98PkeDS/',
    username: '@radarmagelang',
    location: 'Lombok Tengah',
    timeAgo: '10 Mar 2026',
    sentiment: 'negative',
    content: 'Menu MBG bolu kukus di SDN 2 Ketare ditemukan belatung',
    likes: 720,
    comments: 294,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXibavdgeGU',
    url: 'https://www.instagram.com/reel/DXibavdgeGU/',
    username: '@snc.suaranusantara',
    location: 'Jeneponto',
    timeAgo: '26 Apr 2026',
    sentiment: 'negative',
    content: 'Makan ikan dari program MBG. Puluhan siswa di dilarikan ke RS, diduga tak layak konsumsi!',
    likes: 5600,
    comments: 890,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWlREmQkUvx',
    url: 'https://www.instagram.com/reel/DWlREmQkUvx/',
    username: '@tuntasnews',
    location: 'Mataram',
    timeAgo: '13 Feb 2026',
    sentiment: 'negative',
    content: 'Buah busuk di menu MBG SDN 34 Ampenan, orang tua siswa minta evaluasi',
    likes: 1664,
    comments: 625,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVQLiZhEy9s',
    url: 'https://www.instagram.com/reel/DVQLiZhEy9s/',
    username: '@kupassos',
    location: 'Sumatra',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Anak SD keluhkan ke presiden terkait kualitas menu MBG, soroti ketidaksesuain dengan harapan',
    likes: 154000,
    comments: 7681,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWsyMbdE66E',
    url: 'https://www.instagram.com/reel/DWsyMbdE66E/',
    username: '@kupassos',
    location: 'Jakarta',
    timeAgo: '6 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga keracunan MBG di Jakarta Timur, siswa dan guru alami gejala usai konsumsi spaghetti',
    likes: 1054,
    comments: 400,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXLb8xEkqWf',
    url: 'https://www.instagram.com/reel/DXLb8xEkqWf/',
    username: '@gizi.kita',
    location: 'Pontianak',
    timeAgo: '1 hari lalu',
    sentiment: 'negative',
    content: 'Temuan terbaru di Kalimantan: keterlambatan pasokan bahan baku pengaruhi kualitas MBG pekan ini',
    likes: 1054,
    comments: 400,
    platform: 'instagram',
    source: 'instagram',
  },
];

export const tiktokPosts: SocialPost[] = [
  {
    id: 'ZS9SFwXDA',
    url: 'https://vt.tiktok.com/ZS9SFwXDA/',
    username: '@officiallambeturah',
    location: 'Banten',
    timeAgo: '28 Apr 2026',
    sentiment: 'negative',
    content: 'MBG di SD Benda 1 Dibuang karena tidak layak konsumsi',
    likes: 7095,
    comments: 381,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFXXdF',
    url: 'https://vt.tiktok.com/ZS9SFXXdF/',
    username: '@surabayatv',
    location: 'Surabaya',
    timeAgo: '27 Apr 2026',
    sentiment: 'negative',
    content: 'Seorang guru ngamuk tolak MBG yang kerap telat datang di sore hari',
    likes: 180800,
    comments: 1612,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFGWeQ',
    url: 'https://vt.tiktok.com/ZS9SFGWeQ/',
    username: '@detikcom',
    location: 'Jakarta Timur',
    timeAgo: '4 Apr 2026',
    sentiment: 'negative',
    content: '72 Siswa di Jaktim diduga keracunan spageti MBG',
    likes: 3235,
    comments: 237,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFvYAX',
    url: 'https://vt.tiktok.com/ZS9SFvYAX/',
    username: '@wartabromo',
    location: 'Pasuruan',
    timeAgo: '29 Sept 2025',
    sentiment: 'negative',
    content: 'Belatung ditemukan di menu MBG SMKN 1 Bangil Pasuruan',
    likes: 179800,
    comments: 9514,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFCcmw',
    url: 'https://vt.tiktok.com/ZS9SFCcmw/',
    username: '@tribuntimur',
    location: 'Jeneponto',
    timeAgo: '25 Apr 2026',
    sentiment: 'negative',
    content: 'Keracunan MBG di Jeneponto',
    likes: 11900,
    comments: 314,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SYrgAL',
    url: 'https://vt.tiktok.com/ZS9SYrgAL/',
    username: '@infokejadiandemak',
    location: 'Kebonagung',
    timeAgo: '19 Apr 2026',
    sentiment: 'negative',
    content: 'Santri diduga keracunan makanan di Pilangwetan',
    likes: 1011,
    comments: 50,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SjfaoT',
    url: 'https://vt.tiktok.com/ZS9SjfaoT/',
    username: '@ano_cogan',
    location: 'Jeneponto',
    timeAgo: '13 Jan 2026',
    sentiment: 'negative',
    content: 'Tolong ambil keuntungan mikir-mikir',
    likes: 47400,
    comments: 7992,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9Sj48HB',
    url: 'https://vt.tiktok.com/ZS9Sj48HB/',
    username: '@tribuntimur.com',
    location: 'Sulawesi Selatan',
    timeAgo: '25 Apr 2026',
    sentiment: 'negative',
    content: 'Puluhan siswa dan guru keracunan usai makan menu MBG di Jeneponto, siswa menangis dibawa ke puskesmas',
    likes: 11900,
    comments: 314,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SjxXQC',
    url: 'https://vt.tiktok.com/ZS9SjxXQC/',
    username: '@java.tivi',
    location: 'Rembang',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Siswa SD Balongmulyo Kragan keracunan MBG',
    likes: 104,
    comments: 6,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9Sj7HFX',
    url: 'https://vt.tiktok.com/ZS9Sj7HFX/',
    username: '@millenialzkece',
    location: 'Jakarta',
    timeAgo: '22 Apr 2026',
    sentiment: 'negative',
    content: 'Motor listrik MBG ditemukan netizen harganya 10juta, BGN: Akun Bodong itu',
    likes: 27900,
    comments: 893,
    platform: 'tiktok',
    source: 'tiktok',
  },
];

export const newsPosts: SocialPost[] = [
  {
    id: 'news-klaten-keracunan-001',
    url: 'https://www.infonasional.com/keracunan-makan-bergizi-gratis-klaten',
    username: 'Infonasional',
    location: 'Klaten',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Keracunan Makan Bergizi Gratis di Klaten: Sejumlah siswa di Klaten dilaporkan mengalami gejala mual dan muntah setelah mengonsumsi menu MBG. Pihak sekolah langsung membawa siswa ke fasilitas kesehatan terdekat.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-klaten-harianbasis-002',
    url: 'https://www.harianbasis.co/siswa-klaten-keracunan-makan-bergizi',
    username: 'Harian Basis',
    location: 'Klaten',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Siswa Klaten Keracunan Makan Bergizi: Laporan keracunan MBG di Klaten semakin meluas, beberapa siswa dilarikan ke puskesmas setelah mengonsumsi makanan dari program andalan pemerintah ini.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-evaluasi-mbg-003',
    url: 'https://www.infonasional.com/evaluasi-keracunan-makan-bergizi-gratis',
    username: 'Infonasional',
    location: 'Jakarta',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Evaluasi Keracunan MBG: Pemerintah diminta segera melakukan evaluasi menyeluruh terhadap program Makan Bergizi Gratis menyusul rentetan kasus keracunan di berbagai daerah. Standar higiene dan SOP dapur SPPG jadi sorotan utama.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-wantimpres-mbg-004',
    url: 'https://wantimpres.go.id/id/issue/keracunan-mbg/',
    username: 'Wantimpres',
    location: 'Jakarta',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Wantimpres soroti keracunan MBG sebagai isu nasional yang perlu penanganan serius. Dewan Pertimbangan Presiden mendorong perbaikan tata kelola pengadaan dan distribusi makanan bergizi gratis agar kejadian serupa tidak berulang.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-kediri-sppg-005',
    url: 'http://regional.kompas.com/read/2026/04/29/105630678/siswa-kediri-diduga-keracunan-mbg-mas-dhito-ancam-cabut-izin-sppg',
    username: 'Kompas Regional',
    location: 'Kediri',
    timeAgo: '29 Apr 2026',
    sentiment: 'negative',
    content: 'Siswa Kediri Diduga Keracunan MBG, Mas Dhito Ancam Cabut Izin SPPG: Bupati Kediri Hanindhito Himawan Pramana mengancam mencabut izin SPPG Tugurejo setelah enam siswa SD dirawat akibat dugaan keracunan. Sampel makanan dikirim ke laboratorium untuk uji E. coli.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-ugm-33ribu-006',
    url: 'https://ugm.ac.id/id/berita/33-ribu-pelajar-keracunan-mbg-target-3000-porsi-per-sppg-dinilai-melebihi-kapasitas/',
    username: 'UGM.ac.id',
    location: 'Yogyakarta',
    timeAgo: '24 Apr 2026',
    sentiment: 'negative',
    content: '33 Ribu Pelajar Keracunan MBG, Target 3.000 Porsi per SPPG Dinilai Melebihi Kapasitas: Pakar teknologi pangan UGM Prof Sri Raharjo memperingatkan bahwa target produksi 3.000 porsi per hari per SPPG jauh melampaui kapasitas wajar dapur yang baru terbentuk, berpotensi memicu kontaminasi massal.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-icw-markup-007',
    url: 'https://www.law-justice.co/artikel/203332/icw-ungkap-temuan-dugaan-markup-hingga-monopoli-dalam-program-mbg/',
    username: 'Law-Justice.co',
    location: 'Jakarta',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'ICW Ungkap Temuan Dugaan Markup hingga Monopoli dalam Program MBG: Peneliti ICW Eva Nurcahyani mengungkap tiga klaster penyimpangan — anggaran (markup), pengadaan (ketidakwajaran), dan relasi dengan politisi serta aparat hukum — berdasarkan pemantauan di NTB, DIY, dan Bandung.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-sdn-rumak-008',
    url: 'https://rri.co.id/mataram/asta-cita/2374038/dua-pekan-terhenti-mbg-di-sdn-3-rumak-kini-kembali-normal',
    username: 'RRI Mataram',
    location: 'Mataram, NTB',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Dua Pekan Terhenti, MBG di SDN 3 Rumak Kini Kembali Normal: Program MBG di SDN 3 Rumak sempat terhenti selama dua pekan setelah SPPG setempat dihentikan operasionalnya. Distribusi makanan baru kembali berjalan setelah evaluasi dan perbaikan standar.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-sd29-mataram-009',
    url: 'https://suarantb.com/2026/04/28/sppg-dihentikan-sementara-murid-dan-guru-di-sd-29-mataram-tak-terima-mbg-hampir-sebulan/',
    username: 'Suara NTB',
    location: 'Mataram',
    timeAgo: '28 Apr 2026',
    sentiment: 'negative',
    content: 'SPPG Dihentikan Sementara, Murid dan Guru di SD 29 Mataram Tak Terima MBG Hampir Sebulan: Siswa dan tenaga pengajar di SD 29 Mataram terpaksa melewatkan program MBG selama hampir sebulan menyusul penghentian sementara operasional SPPG di wilayah tersebut.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-demak-ibumenyusui-010',
    url: 'https://regional.kompas.com/read/2026/04/20/110825478/diduga-keracunan-mbg-di-demak-ibu-menyusui-alami-mual-ratusan-santri',
    username: 'Kompas Regional',
    location: 'Demak, Jawa Tengah',
    timeAgo: '20 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG di Demak, Ibu Menyusui Alami Mual, Ratusan Santri Terdampak: Ratusan santri di Desa Pilangwetan Kebonagung Demak mengalami mual, muntah, dan diare setelah mengonsumsi nasi goreng MBG yang didistribusikan pada 18 April 2026. Ibu hamil dan menyusui turut terdampak.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-deliserdang-12siswa-011',
    url: 'https://medan.kompas.com/read/2026/04/29/080316778/12-siswa-sd-di-deli-serdang-keracunan-usai-santap-mbg-bgn-sppg-kami-pastikan',
    username: 'Kompas Medan',
    location: 'Deli Serdang, Sumatra Utara',
    timeAgo: '29 Apr 2026',
    sentiment: 'negative',
    content: '12 Siswa SD di Deli Serdang Keracunan Usai Santap MBG: Sebanyak 12 siswa SD Swasta As Syifa diduga keracunan menu ayam bakar MBG. BGN Sumut memastikan SPPG Pagar Merbau Tanjung Garbus 2 dihentikan operasional sementara sambil menunggu hasil uji laboratorium.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-demak-76penerima-012',
    url: 'https://regional.kompas.com/read/2026/04/21/195029178/76-penerima-mbg-alami-keracunan-di-demak-61-masih-dirawat-di-rumah-sakit',
    username: 'Kompas Regional',
    location: 'Demak, Jawa Tengah',
    timeAgo: '21 Apr 2026',
    sentiment: 'negative',
    content: '76 Penerima MBG Alami Keracunan di Demak, 61 Masih Dirawat di RS: Investigasi awal menduga keracunan akibat keterlambatan konsumsi — nasi goreng dimasak pukul 03.00 WIB, baru dikonsumsi sore hari, dan kombinasi susu dengan jeruk memperparah gangguan pencernaan.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-deliserdang-11siswa-013',
    url: 'https://mistar.id/news/hukum-peristiwa/diduga-keracunan-mbg-11-siswa-sd-di-deli-serdang-dilarikan-ke-puskesmas',
    username: 'Mistar.id',
    location: 'Deli Serdang, Sumatra Utara',
    timeAgo: '28 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG, 11 Siswa SD di Deli Serdang Dilarikan ke Puskesmas: Sebelas siswa kelas 6 SD Swasta Terpadu As Syifa dilarikan ke Puskesmas Pagar Merbau setelah mengeluhkan sakit perut dan muntah usai menyantap ayam bakar dari menu MBG.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-demak-dpd-014',
    url: 'http://regional.kompas.com/read/2026/04/29/051618378/ratusan-warga-demak-keracunan-mbg-dpd-ri-dorong-perbaikan-tata-kelola-dan',
    username: 'Kompas Regional',
    location: 'Demak, Jawa Tengah',
    timeAgo: '29 Apr 2026',
    sentiment: 'negative',
    content: 'Ratusan Warga Demak Keracunan MBG, DPD RI Dorong Perbaikan Tata Kelola: DPD RI mendesak evaluasi menyeluruh sistem distribusi dan pengawasan MBG pasca kasus keracunan massal yang menimpa 187 warga Desa Pilangwetan, termasuk balita dan ibu menyusui.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-rembang-sdn-klarifikasi-015',
    url: 'https://timesindonesia.co.id/peristiwa-daerah/586607/dugaan-keracunan-di-sdn-balong-mulyo-rembang-mitra-dapur-mbg-beri-klarifikasi',
    username: 'Times Indonesia',
    location: 'Rembang, Jawa Tengah',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'Dugaan Keracunan di SDN Balong Mulyo Rembang, Mitra Dapur MBG Beri Klarifikasi: Mitra dapur SPPG Rembang memberikan penjelasan menyusul laporan puluhan siswa SDN Balongmulyo yang mengalami pusing dan sesak usai mengonsumsi susu MBG yang menurut saksi sudah terasa kecut.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-rembang-22siswa-016',
    url: 'https://semarang.viva.co.id/berita/6843-diduga-keracun22-siswa-sd-di-rembang-dilarikan-ke-puskesmas-setelah-makan-menu-mbg',
    username: 'VIVA Semarang',
    location: 'Rembang, Jawa Tengah',
    timeAgo: '21 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan, 22 Siswa SD di Rembang Dilarikan ke Puskesmas Setelah Makan Menu MBG: Puluhan siswa SDN Balongmulyo Kragan yang mengenakan kostum kebaya untuk peringatan Hari Kartini harus dilarikan ke Puskesmas Kragan II setelah mengonsumsi susu MBG yang diduga bermasalah.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-kediri-bupati-sppg-017',
    url: 'https://www.detik.com/jatim/berita/d-8465373/bupati-kediri-pastikan-sppg-disetop-usai-dugaan-keracunan-mbg-di-ngasem',
    username: 'Detik Jatim',
    location: 'Kediri, Jawa Timur',
    timeAgo: '28 Apr 2026',
    sentiment: 'negative',
    content: 'Bupati Kediri Pastikan SPPG Disetop Usai Dugaan Keracunan MBG di Ngasem: Bupati Kediri Hanindhito Himawan Pramana memastikan SPPG Tugurejo dihentikan sementara setelah enam siswa dirawat di RSUD Simpang Lima Gumul. Lima dari enam siswa masih dirawat karena leukosit masih tinggi.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-rembang-kartini-018',
    url: 'https://www.detik.com/jateng/berita/d-8454362/puluhan-siswa-sd-di-rembang-diduga-keracunan-mbg-acara-kartinian-gagal-total',
    username: 'Detik Jateng',
    location: 'Rembang, Jawa Tengah',
    timeAgo: '21 Apr 2026',
    sentiment: 'negative',
    content: 'Puluhan Siswa SD di Rembang Diduga Keracunan MBG, Acara Kartinian Gagal Total: Perayaan Hari Kartini di SDN Balongmulyo Kragan berubah jadi bencana. Para siswa yang mengenakan kebaya harus beristirahat di puskesmas setelah mengonsumsi susu MBG yang sudah melewati batas aman konsumsi.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-cianjur-balita-meninggal-019',
    url: 'https://pontianakpost.jawapos.com/nasional/2604270003/balita-di-cianjur-meninggal-diduga-keracunan-makan-bergizi-gratis-dinkes-lakukan-penyelidikan',
    username: 'Pontianak Post / JawaPos',
    location: 'Cianjur, Jawa Barat',
    timeAgo: '25 Apr 2026',
    sentiment: 'negative',
    content: 'Balita di Cianjur Meninggal Diduga Keracunan Makan Bergizi Gratis, Dinkes Lakukan Penyelidikan: Seorang balita berusia 2 tahun dilaporkan meninggal dunia setelah sempat dirawat dengan gejala yang diduga berkaitan dengan konsumsi MBG. Dinas Kesehatan Cianjur langsung membentuk tim investigasi dan mengirimkan sampel ke laboratorium.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
  {
    id: 'news-bgn-bantah-cianjur-020',
    url: 'https://bengkulu.antaranews.com/berita/466917/bgn-bantah-balita-di-cianjur-meninggal-akibat-makan-bergizi-gratis',
    username: 'Antara Bengkulu',
    location: 'Cianjur / Jakarta',
    timeAgo: 'Apr 2026',
    sentiment: 'negative',
    content: 'BGN Bantah Balita di Cianjur Meninggal Akibat Makan Bergizi Gratis: Badan Gizi Nasional (BGN) membantah kabar bahwa balita yang meninggal di Cianjur disebabkan konsumsi MBG. BGN menyatakan masih menunggu hasil resmi dari Dinas Kesehatan dan laboratorium sebelum menarik kesimpulan.',
    likes: 0,
    comments: 0,
    platform: 'news',
    source: 'news',
  },
];

export const allSocialPosts: SocialPost[] = [
  ...twitterPosts,
  ...instagramPosts,
  ...tiktokPosts,
  ...newsPosts,
];

export const getPostsByPlatform = (platform: Platform | 'all') => {
  if (platform === 'all') return allSocialPosts;
  return allSocialPosts.filter((p) => p.platform === platform);
};

export const criticalPosts = allSocialPosts.filter(
  (p) => p.sentiment === 'negative'
);

export const positivePosts = allSocialPosts.filter(
  (p) => p.sentiment === 'positive'
);