export type Sentiment = 'positive' | 'negative' | 'neutral';
export type Platform = 'twitter' | 'instagram' | 'tiktok';
export type Source = 'web' | 'instagram' | 'tiktok';

export interface SocialPost {
  id: string;
  url: string;
  username: string;
  location: string;
  timeAgo: string;
  sentiment: Sentiment;
  content: string;
  likes: number;
  comments: number;
  platform: Platform;
  source: Source;
}

export const twitterPosts: SocialPost[] = [
  {
    id: '2048333766867730476',
    url: 'https://x.com/i/status/2048333766867730476',
    username: '@SINDOnews',
    location: 'Jakarta',
    timeAgo: '4:30 PM · 26 Apr 2026',
    sentiment: 'negative',
    content: 'Temuan pengurangan porsi dalam program Makan Bergizi Gratis (MBG) jadi sorotan. Sekitar 1.700 SPPG dihentikan sementara untuk evaluasi karena ada menu di bawah standar gizi. Hal ini berpotensi menurunkan kualitas asupan anak. #MBG #MakanBergiziGratis #GiziAnak',
    likes: 0,
    comments: 0,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2048056231928217678',
    url: 'https://x.com/i/status/2048056231928217678',
    username: '@ferizandra',
    location: 'Cianjur',
    timeAgo: '10:07 · 25 Apr 2026',
    sentiment: 'negative',
    content: 'Kasus dugaan keracunan terkait program MBG di Cianjur menjadi perhatian. Seorang balita (2 tahun) dilaporkan meninggal dunia setelah dirawat, sementara puluhan lainnya mengalami gejala serupa. Dinas Kesehatan masih menunggu hasil laboratorium untuk memastikan penyebabnya. #MBG #Cianjur #GiziAnak',
    likes: 1500,
    comments: 83,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047900199478350079',
    url: 'https://x.com/i/status/2047900199478350079',
    username: '@MurtadhaOne1',
    location: 'Jeneponto, Lombok Timur',
    timeAgo: '11:47 AM · 23 Apr 2026',
    sentiment: 'negative',
    content: 'Kasus dugaan keracunan terkait program MBG kembali menjadi sorotan di berbagai daerah. Laporan muncul dari Jeneponto (23 April) dan Lombok Timur (24 April), memicu kekhawatiran masyarakat terkait keamanan makanan yang diberikan kepada anak-anak. #MBG #KeamananPangan',
    likes: 412,
    comments: 218,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047594344832721093',
    url: 'https://x.com/i/status/2047594344832721093',
    username: '@menuembegejelek',
    location: 'Pangadaan, Lombok Timur',
    timeAgo: '2 jam lalu',
    sentiment: 'negative',
    content: '22 Siswa SD di Lombok Timur Diduga Keracunan Makanan MBG, Alami Mual hingga Kejang',
    likes: 17,
    comments: 715,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2047569872108892629',
    url: 'https://x.com/i/status/2047569872108892629',
    username: '@ferizandra',
    location: 'Pringgasela, Lombok Timur',
    timeAgo: '1:54 PM · Apr 24 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG, 21 Siswa di Lombok Timur Alami Mual dan Muntah Usai Konsumsi Makanan',
    likes: 16,
    comments: 3,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2045748700795019647',
    url: 'https://x.com/i/status/2045748700795019647',
    username: '@menuemebegejelek',
    location: 'Cilegon, Banten',
    timeAgo: '16 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga Keracunan MBG di Cilegon, 49 Siswa MTs Al-Inayah Alami Mual dan Muntah, Puluhan Dirawat',
    likes: 255,
    comments: 8300,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2045034527870087508',
    url: 'https://x.com/i/status/2045034527870087508',
    username: '@tempodotco',
    location: 'Jakarta',
    timeAgo: '2:00 PM · 17 Apr 2026',
    sentiment: 'negative',
    content: 'Anggaran BGN Disorot, Rp1,5 Miliar Dihabiskan untuk Sikat dan Semir Sepatu',
    likes: 23000,
    comments: 3000,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042766137591763322',
    url: 'https://x.com/i/status/2042766137591763322',
    username: '@SumandoGaek',
    location: 'Jakarta',
    timeAgo: '7:46 AM · 11 Apr 2026',
    sentiment: 'negative',
    content: 'Anggaran MBG Diduga Bermasalah, Potensi Penyimpangan Disebut Terjadi pada Biaya Porsi Makanan',
    likes: 10,
    comments: 0,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042509805462655484',
    url: 'https://x.com/i/status/2042509805462655484',
    username: '@is_pelssy',
    location: 'Jambi',
    timeAgo: '1 hari lalu',
    sentiment: 'negative',
    content: 'Cicipi MBG Sebelum Dibagikan, 3 Guru Di SMPN 7 Jambi Keracunan Dan Dilarikan ke Rumah Sakit',
    likes: 6600,
    comments: 643,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042461329064415463',
    url: 'https://x.com/i/status/2042461329064415463',
    username: '@Txtdariiugm',
    location: 'Yogyakarta',
    timeAgo: '11:35 AM · Apr 10',
    sentiment: 'negative',
    content: 'Anggaran MBG Rp10 Ribu per Porsi Disorot, Dinilai Tidak Sebanding dengan Kualitas Makanan',
    likes: 9700,
    comments: 128,
    platform: 'twitter',
    source: 'web',
  },
  {
    id: '2042303365821116922',
    url: 'https://x.com/i/status/2042303365821116922',
    username: '@SumandoGaek',
    location: 'Medan',
    timeAgo: '1:07 AM · Apr 10 2026',
    sentiment: 'negative',
    content: 'Laporan dari Medan: Orang Tua di Medan Keluhkan Porsi MBG untuk Anak TK, Dinilai Tidak Layak dan Minim Gizi',
    likes: 4400,
    comments: 220,
    platform: 'twitter',
    source: 'web',
  },
];

export const instagramPosts: SocialPost[] = [
  {
    id: 'DXjetRFEith',
    url: 'https://www.instagram.com/reel/DXjetRFEith/',
    username: '@otistanews',
    location: 'Benteng, Bengkulu',
    timeAgo: '24 Apr 2026',
    sentiment: 'negative',
    content: 'Ayam terlihat fresh tapi berulat SPPG Kembang Seri distop, dugaan keracunan mencuat',
    likes: 1121,
    comments: 335,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXbNp3RERej',
    url: 'https://www.instagram.com/reel/DXbNp3RERej/',
    username: '@komunitaskabarmadura',
    location: 'Madura',
    timeAgo: '22 Apr 2026',
    sentiment: 'negative',
    content: 'Siswa di SDN Bira Tengah Sokobana Sampang usai makan MBG langsung alergi kulit, tiba-tiba merasa gatal-gatal',
    likes: 6558,
    comments: 1059,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVd2Lg1Ee5v',
    url: 'https://www.instagram.com/reel/DVd2Lg1Ee5v/',
    username: '@info.jabodetabek',
    location: 'Depok',
    timeAgo: '2 jam yang lalu',
    sentiment: 'negative',
    content: 'Menu MBG di Cinangka disorot, timun utuh dinilai kurang praktis untuk anak',
    likes: 6679,
    comments: 1944,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWl5cMSk6VO',
    url: 'https://www.instagram.com/reel/DWl5cMSk6VO/',
    username: '@tuntasnews',
    location: 'Cianjur',
    timeAgo: '6 Apr 2026',
    sentiment: 'negative',
    content: 'Menu MBG di Cianjur diduga ayam bau bangkai, siswa terancam',
    likes: 5790,
    comments: 1971,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVLRLL_Eeq7',
    url: 'https://www.instagram.com/reel/DVLRLL_Eeq7/',
    username: '@radarbromo',
    location: 'Magetan',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Kotor dan retak! telur MBG di Magetan di rebus masih ada kotoran ayam',
    likes: 69400,
    comments: 12100,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVvB98PkeDS',
    url: 'https://www.instagram.com/reel/DVvB98PkeDS/',
    username: '@radarmagelang',
    location: 'Lombok Tengah',
    timeAgo: '10 Mar 2026',
    sentiment: 'negative',
    content: 'Menu MBG bolu kukus di SDN 2 Ketare ditemukan belatung',
    likes: 720,
    comments: 294,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXibavdgeGU',
    url: 'https://www.instagram.com/reel/DXibavdgeGU/',
    username: '@snc.suaranusantara',
    location: 'Jeneponto',
    timeAgo: '26 Apr 2026',
    sentiment: 'negative',
    content: 'Makan ikan dari program MBG. Puluhan siswa di dilarikan ke RS, diduga tak layak konsumsi!',
    likes: 5600,
    comments: 890,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWlREmQkUvx',
    url: 'https://www.instagram.com/reel/DWlREmQkUvx/',
    username: '@tuntasnews',
    location: 'Mataram',
    timeAgo: '13 Feb 2026',
    sentiment: 'negative',
    content: 'Buah busuk di menu MBG SDN 34 Ampenan, orang tua siswa minta evaluasi',
    likes: 1664,
    comments: 625,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DVQLiZhEy9s',
    url: 'https://www.instagram.com/reel/DVQLiZhEy9s/',
    username: '@kupassos',
    location: 'Sumatra',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Anak SD keluhkan ke presiden terkait kualitas menu MBG, soroti ketidaksesuain dengan harapan',
    likes: 154000,
    comments: 7681,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DWsyMbdE66E',
    url: 'https://www.instagram.com/reel/DWsyMbdE66E/',
    username: '@kupassos',
    location: 'Jakarta',
    timeAgo: '6 Apr 2026',
    sentiment: 'negative',
    content: 'Diduga keracunan MBG di Jakarta Timur, siswa dan guru alami gejala usai konsumsi spaghetti',
    likes: 1054,
    comments: 400,
    platform: 'instagram',
    source: 'instagram',
  },
  {
    id: 'DXLb8xEkqWf',
    url: 'https://www.instagram.com/reel/DXLb8xEkqWf/',
    username: '@gizi.kita',
    location: 'Pontianak',
    timeAgo: '1 hari lalu',
    sentiment: 'negative',
    content: 'Temuan terbaru di Kalimantan: keterlambatan pasokan bahan baku pengaruhi kualitas MBG pekan ini',
    likes: 1054,
    comments: 400,
    platform: 'instagram',
    source: 'instagram',
  },
];

export const tiktokPosts: SocialPost[] = [
  {
    id: 'ZS9SFwXDA',
    url: 'https://vt.tiktok.com/ZS9SFwXDA/',
    username: '@officiallambeturah',
    location: 'Banten',
    timeAgo: '28 Apr 2026',
    sentiment: 'negative',
    content: 'MBG di SD Benda 1 Dibuang karena tidak layak konsumsi',
    likes: 7095,
    comments: 381,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFXXdF',
    url: 'https://vt.tiktok.com/ZS9SFXXdF/',
    username: '@surabayatv',
    location: 'Surabaya',
    timeAgo: '27 Apr 2026',
    sentiment: 'negative',
    content: 'Seorang guru ngamuk tolak MBG yang kerap telat datang di sore hari',
    likes: 180800,
    comments: 1612,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFGWeQ',
    url: 'https://vt.tiktok.com/ZS9SFGWeQ/',
    username: '@detikcom',
    location: 'Jakarta Timur',
    timeAgo: '4 Apr 2026',
    sentiment: 'negative',
    content: '72 Siswa di Jaktim diduga keracunan spageti MBG',
    likes: 3235,
    comments: 237,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFvYAX',
    url: 'https://vt.tiktok.com/ZS9SFvYAX/',
    username: '@wartabromo',
    location: 'Pasuruan',
    timeAgo: '29 Sept 2025',
    sentiment: 'negative',
    content: 'Belatung ditemukan di menu MBG SMKN 1 Bangil Pasuruan',
    likes: 179800,
    comments: 9514,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SFCcmw',
    url: 'https://vt.tiktok.com/ZS9SFCcmw/',
    username: '@tribuntimur',
    location: 'Jeneponto',
    timeAgo: '25 Apr 2026',
    sentiment: 'negative',
    content: 'Keracunan MBG di Jeneponto',
    likes: 11900,
    comments: 314,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SYrgAL',
    url: 'https://vt.tiktok.com/ZS9SYrgAL/',
    username: '@infokejadiandemak',
    location: 'Kebonagung',
    timeAgo: '19 Apr 2026',
    sentiment: 'negative',
    content: 'Santri diduga keracunan makanan di Pilangwetan',
    likes: 1011,
    comments: 50,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SjfaoT',
    url: 'https://vt.tiktok.com/ZS9SjfaoT/',
    username: '@ano_cogan',
    location: 'Jeneponto',
    timeAgo: '13 Jan 2026',
    sentiment: 'negative',
    content: 'Tolong ambil keuntungan mikir-mikir',
    likes: 47400,
    comments: 7992,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9Sj48HB',
    url: 'https://vt.tiktok.com/ZS9Sj48HB/',
    username: '@tribuntimur.com',
    location: 'Sulawesi Selatan',
    timeAgo: '25 Apr 2026',
    sentiment: 'negative',
    content: 'Puluhan siswa dan guru keracunan usai makan menu MBG di Jeneponto, siswa menangis dibawa ke puskesmas',
    likes: 11900,
    comments: 314,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9SjxXQC',
    url: 'https://vt.tiktok.com/ZS9SjxXQC/',
    username: '@java.tivi',
    location: 'Rembang',
    timeAgo: '27 Feb 2026',
    sentiment: 'negative',
    content: 'Siswa SD Balongmulyo Kragan keracunan MBG',
    likes: 104,
    comments: 6,
    platform: 'tiktok',
    source: 'tiktok',
  },
  {
    id: 'ZS9Sj7HFX',
    url: 'https://vt.tiktok.com/ZS9Sj7HFX/',
    username: '@millenialzkece',
    location: 'Jakarta',
    timeAgo: '22 Apr 2026',
    sentiment: 'negative',
    content: 'Motor listrik MBG ditemukan netizen harganya 10juta, BGN: Akun Bodong itu',
    likes: 27900,
    comments: 893,
    platform: 'tiktok',
    source: 'tiktok',
  },
];

export const allSocialPosts: SocialPost[] = [
  ...twitterPosts,
  ...instagramPosts,
  ...tiktokPosts,
];

export const criticalPosts = allSocialPosts.filter(
  (p) => p.sentiment === 'negative'
);

export const positivePosts = allSocialPosts.filter(
  (p) => p.sentiment === 'positive'
);